### ISSUE TITLE
Unable to Log in -> Getting crash

### ISSUE THREAD

**Issue by mohitmanuja** [twilio/twilio-chat-demo-android#130]
### Description

On click of login, app is getting crashed.

### Steps to Reproduce

1. Run app.
2. Click on log in. 

#### Logs

Process: com.twilio.chat.demo.debug, PID: 22990
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/getkeepsafe/relinker/ReLinker;
        at com.twilio.chat.ChatClient.loadNativeLibraries(ChatClient.java:183)
        at com.twilio.chat.ChatClient.<init>(ChatClient.java:373)
        at com.twilio.chat.ChatClient.create(ChatClient.java:284)
        at com.twilio.chat.demo.BasicChatClient.createClient(BasicChatClient.kt:139)
        at com.twilio.chat.demo.BasicChatClient.access$createClient(BasicChatClient.kt:17)

`

**Comment by rusmonster** [comment]
cannot reproduce this yet. 
please try to clean and rebuild the project:
```
./gradlew clean assembleDebug
```

**Comment by mohitmanuja** [comment]
@rusmonster Yes, fixed now.
