### ISSUE TITLE
App crash during shutdown

### ISSUE THREAD

**Issue by DimaLizunov** [twilio/twilio-chat-demo-android#23]
Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[62,tid=10325,Native,Thread*=0xb88d1920,peer=0x2334a100,"allenges - 8539 - 10325"]
Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[62,tid=10343,Native,Thread*=0xb890a4f0,peer=0x2334a160,"allenges - 8539 - 10343"]
Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[64,tid=10349,Native,Thread*=0xb88d1920,peer=0x2334a1c0,"allenges - 8539 - 10349"]
Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[62,tid=10355,Native,Thread*=0xb890a4f0,peer=0x2334a220,"allenges - 8539 - 10355"]
Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[64,tid=10358,Native,Thread*=0xb88d1920,peer=0x2334a280,"allenges - 8539 - 10358"]
Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[62,tid=10360,Native,Thread*=0xb890a4f0,peer=0x2334a2e0,"allenges - 8539 - 10360"]
Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[64,tid=10361,Native,Thread*=0xb88d1920,peer=0x2334a340,"allenges - 8539 - 10361"]
Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[62,tid=10369,Native,Thread*=0xb890a4f0,peer=0x2334a3a0,"allenges - 8539 - 10369"]
Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[62,tid=10377,Native,Thread*=0xb890a4f0,peer=0x2334a400,"allenges - 8539 - 10377"]
Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[62,tid=10391,Native,Thread*=0xb890a4f0,peer=0x2334a460,"allenges - 8539 - 10391"]
Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[64,tid=10394,Native,Thread*=0xb887e050,peer=0x2334a4c0,"allenges - 8539 - 10394"]
Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[62,tid=10408,Native,Thread*=0xb84dd608,peer=0x23351100,"allenges - 8539 - 10408"]
Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[65,tid=10412,Native,Thread*=0xb890a4f0,peer=0x2334a520,"allenges - 8539 - 10412"]
Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[64,tid=10419,Native,Thread*=0xb84dd608,peer=0x23351160,"allenges - 8539 - 10419"]
Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[62,tid=10415,Native,Thread*=0xb887e050,peer=0x2334a580,"allenges - 8539 - 10415"]
Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[65,tid=10424,Native,Thread*=0xb890a4f0,peer=0x233511c0,"allenges - 8539 - 10424"]
Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[62,tid=10425,Native,Thread*=0xb84dd608,peer=0x2334a5e0,"allenges - 8539 - 10425"]
Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[64,tid=10426,Native,Thread*=0xb887e050,peer=0x23351220,"allenges - 8539 - 10426"]

**Comment by berkus** [comment]
These messages are harmless, is there an actual crash backtrace? Logs?

**Comment by DimaLizunov** [comment]
oh, i am sorry. I did not understand your manual for report correctly
11-01 16:47:03.708 7196-7196/ E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: PID: 7196
                                                                    java.lang.RuntimeException: Unable to destroy activity {/com.outdoo.ui.direct.chat.ChatActivity}: java.lang.IllegalStateException: Attempt to use disposed object in ChatClient#shutdown
                                                                        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3812)
                                                                        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3830)
                                                                        at android.app.ActivityThread.access$1400(ActivityThread.java:156)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:211)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5371)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:372)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:945)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:740)
                                                                     Caused by: java.lang.IllegalStateException: Attempt to use disposed object in ChatClient#shutdown
                                                                        at com.twilio.chat.ChatClient.checkDisposed(ChatClient.java:553)
                                                                        at com.twilio.chat.ChatClient.shutdown(ChatClient.java:441)
                                                                        at com.outdoo.data.chat.twillio.TwillioMessagingClient.disconnect(TwillioMessagingClient.java:70)
                                                                        at com.outdoo.ui.direct.chat.ChatPresenter.detachFromView(ChatPresenter.kt:30)
                                                                        at com.outdoo.ui.base.inject.BaseInjectActivity.onDestroy(BaseInjectActivity.kt:26)
                                                                        at android.app.Activity.performDestroy(Activity.java:6169)
                                                                        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1141)
                                                                        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3799)
                                                                        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3830) 
                                                                        at android.app.ActivityThread.access$1400(ActivityThread.java:156) 
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                        at android.os.Looper.loop(Looper.java:211) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5371) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:945) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:740)

**Comment by berkus** [comment]
> Attempt to use disposed object in ChatClient#shutdown

You have shut down ChatClient and then try to shutdown it again.

**Comment by DimaLizunov** [comment]
I can send all logs, when app is crashing

**Comment by berkus** [comment]
Just don't reuse ChatClient after shutdown.

**Comment by berkus** [comment]
Closing, please reopen if you have further questions.
