### ISSUE TITLE
java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String com.twilio.chat.Channel.getSid()

### ISSUE THREAD

**Issue by InI4** [twilio/twilio-chat-demo-android#44]
### Description

This is from crashlytics reports.

#### Expected Behavior

API call should work.

#### Actual Behavior

API call does not work.

#### Reproduces how Often

From the crashlytics numbers, the test user with the given Hardware is affected often.

#### Logs

```
D/bdg.globs eLog: ! Crashed Thread[main,5,main] java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String com.twilio.chat.Channel.getSid() (tried Java_com_twilio_chat_Channel_getSid and Java_com_twilio_chat_Channel_getSid__) at com.twilio.chat.Channel.getSid(Native Method) at de.spieleck.app.badgers.chat.twilio.MessageActivity.sl(sf:220) at de.spieleck.app.badgers.chat.twilio.MessageActivity.onResume(sf:1181) at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1355) at android.app.Activity.performResume(Activity.java:7107) at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3556) at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3621) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2862) at android.app.ActivityThread.-wrap11(Unknown Source:0) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loop(Looper.java:164) at android.app.ActivityThread.main(ActivityThread.java:6494) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
```

Or attach it as a file.

#### Chat Android SDK

2.0.8

#### Android API

8.1 in all cases so far

#### Android Device

Pixel XL in all cases so far

**Comment by berkus** [comment]
Thx, filed it, will investigate.

**Comment by berkus** [comment]
Hi,

What hardware architecture is this?

**Comment by InI4** [comment]
I've seen this on all kinds of devices, my own ones, emulators but also in the crashlytics reports of my app.
But with 4.0 soon coming, lets wait for this.

**Comment by berkus** [comment]
Closing, this should be gone in 4.0.0.
