### ISSUE TITLE
Failed adding to JNI local ref table (has 512 entries)

### ISSUE THREAD

**Issue by laiis** [twilio/twilio-chat-demo-android#47]
> Before filing an issue please check that the issue is not already addressed by the following:
>  * [Github Issues](https://github.com/twilio/twilio-chat-demo-android/issues)
>  * [Changelog](https://www.twilio.com/docs/api/chat/changelogs/android)

### Description
I made a app used twilio chat library
When I review my chat records, and back to prev page , then app got crash.
I checked the logs , and found some question about JNI local ref table (has 512 entries)
Plz help me 
thank you.

### Steps to Reproduce

1.  into chatroom
2.  retrive  messages (history), 50 records limit.
3.  back and shutdown the chatclient , then  got crash

#### Expected Behavior

no crash 

#### Actual Behavior

crash

#### Reproduces how Often

every time, 

#### Logs

05-11 11:15:24.667 24974-24974/xxx.yyy E/dalvikvm: JNI ERROR (app bug): local reference table overflow (max=512)
05-11 11:15:24.667 24974-24974/xxx.yyy W/dalvikvm: JNI local reference table (0x62a14d20) dump:
      Last 10 entries (of 512):
          511: 0x430213c8 com.twilio.chat.Message
          510: 0x436700b0 java.lang.Class<com.twilio.chat.Message>
          509: 0x436700b0 java.lang.Class<com.twilio.chat.Message>
          508: 0x436700b0 java.lang.Class<com.twilio.chat.Message>
          507: 0x436700b0 java.lang.Class<com.twilio.chat.Message>
          506: 0x436700b0 java.lang.Class<com.twilio.chat.Message>
          505: 0x436700b0 java.lang.Class<com.twilio.chat.Message>
          504: 0x436700b0 java.lang.Class<com.twilio.chat.Message>
          503: 0x436700b0 java.lang.Class<com.twilio.chat.Message>
          502: 0x436700b0 java.lang.Class<com.twilio.chat.Message>
      Summary:
          506 of java.lang.Class (5 unique instances)
            2 of java.lang.String (2 unique instances)
            1 of java.lang.String[] (2 elements)
            1 of com.twilio.chat.ChatClient
            1 of com.twilio.chat.Channel
            1 of com.twilio.chat.Message
05-11 11:15:24.667 24974-24974/xxx.yyy E/dalvikvm: Failed adding to JNI local ref table (has 512 entries)
05-11 11:15:24.667 24974-24974/xxx.yyy I/dalvikvm: "main" prio=5 tid=1 RUNNABLE
      | group="main" sCount=0 dsCount=0 obj=0x416eee58 self=0x41606bd0
      | sysTid=24974 nice=0 sched=0/0 cgrp=apps handle=1074389332
      | state=R schedstat=( 51876299746 4146432040 59892 ) utm=4814 stm=373 core=0
        at com.twilio.chat.Message.nativeDispose(Native Method)
        at com.twilio.chat.Message.nativeDispose(Native Method)
        at com.twilio.chat.Message.dispose(Message.java:416)
        at com.twilio.chat.Channel.nativeDispose(Native Method)
        at com.twilio.chat.Channel.nativeDispose(Native Method)
        at com.twilio.chat.Channel.dispose(Channel.java:597)
        at com.twilio.chat.ChatClient.nativeDispose(Native Method)
        at com.twilio.chat.ChatClient.nativeDispose(Native Method)
        at com.twilio.chat.ChatClient.dispose(ChatClient.java:546)
        at com.twilio.chat.ChatClient.shutdown(ChatClient.java:476)
        at xxx.BasicChatClient.shutdown(BasicChatClient.java:123)
        at xxx.TwilioHistoryManager.reset(TwilioHistoryManager.java:288)
        at xxx.yyy.zzz.helpers.TwilioHistoryManager.reset(TwilioHistoryManager.java:299)
        at xxx.yyy.zzz.activities.ChatListActivity.onOptionsItemSelected(ChatListActivity.java:145)
        at android.app.Activity.onMenuItemSelected(Activity.java:2670)
        at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:408)
        at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
        at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:113)
        at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:113)
        at android.support.v7.widget.ToolbarWidgetWrapper$1.onClick(ToolbarWidgetWrapper.java:187)
        at android.view.View.performClick(View.java:4496)
05-11 11:15:24.677 24974-24974/xxx.yyy I/dalvikvm:     at android.view.View$PerformClick.run(View.java:18603)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5433)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
        at dalvik.system.NativeStart.main(Native Method)
05-11 11:15:24.677 24974-24974/xxx.yyy E/dalvikvm: VM aborting
05-11 11:15:24.677 24974-24974/xxx.yyy A/libc: Fatal signal 6 (SIGABRT) at 0x0000618e (code=-6), thread 24974 (xxx.yyy)

### Versions

All relevant version information for issue.

#### Chat Android SDK

'com.twilio:chat-android:2.0.4'
'com.twilio:voice-android:2.0.4'
'com.twilio:accessmanager-android:0.1.0'

#### Android API

sdk 19  , 23

#### Android Device

SM-G360G
ASUS_ZOOED

**Comment by berkus** [comment]
Thanks for the report.

I see you're using twilio-voice as well? I believe the problem lies in the interaction of these two. Could you try the same app without using voice and confirm it resolves the issue?

I will run local reproduction steps here, but I'm certain i've never seen these with plain chat sdk, so it must be something together with voice.

**Comment by berkus** [comment]
Hi, I've reproduced the problem and have a fix for it. Will release soon.

**Comment by laiis104** [comment]
Yes ! my problem is solved by v2.0.11
thank you!
ps. I found this issues would cause app crash when I shutdown chatclient that has more than 512 records , lower than 512 would not crash .
